force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <label>UUID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProductRestService.cls
@RestResource(urlMapping='/Contact/*')
global with sharing class ProductRestService {

    @HttpGet
    global static Map<String, String> getContactProductImportantData() {
        String contactUUID = RestContext.request.requestURI.split('/')[2];
        
        try{
            Contact contactToProcess = [SELECT Product__c FROM Contact WHERE UUID__c = :contactUUID];

            String response = JSON.serialize(ProductDataProcessor.buildParentProductWrappers(new Set<Id>{contactToProcess.Product__c}));
            System.debug(response);
            return new Map<String, String>{
                'Product Data' => response
            };
        }catch(QueryException e){
            return new Map<String, String>{
                'error' => 'The specified UUID is not related to any contact'
            };
        }
    }
}